indicators_dict = {
    "Volume-Based Indicators": {
        "AccumDist": {},
        "AccumDistBuyPr": {},
        "AccumDistPrVol": {},
        "OnBalanceVolume": {},
        "OnBalanceVolumeModified": {},
        "VolumeAccumulation": {},
        "VolumeFlowIndicator": {},
        "VolumeOsc": {},
        "VolumeProfile": {},
        "VolumeRateOfChange": {},
        "VolumeWeightedMACD": {},
        "VWAP": {},
        "CumulativeVolumeIndex": {},
        "CumulativeOvernightVolume": {},
        "NegativeVolumeIndex": {},
        "PositiveVolumeIndex": {},
        "VolumeZoneOscillator": {},
        "VortexIndicator": {}
    },
    "Trend Indicators": {
        "ADX": {},
        "ADXBreakoutsFilter": {},
        "ADXCrossover": {},
        "ADXR": {},
        "AroonIndicator": {},
        "AroonOscillator": {},
        "DMA": {},
        "DMI": {},
        "DMI_Oscillator": {},
        "ParabolicSAR": {},
        "ParabolicSARCrossover": {},
        "PriceOsc": {},
        "TrendNoiseBalance": {},
        "TRIX": {},
        "TrueStrengthIndex": {},
        "MarketSentiment": {},
        "OnsetTrendDetector": {},
        "PolarizedFractalEfficiency": {},
        "RainbowAverage": {},
        "RegressionDivergence": {},
        "RelativeMomentumIndex": {},
        "RelativeStrength": {},
        "RelativeStrengthIndex": {},
        "RSI": {},
        "RSICrossover": {},
        "RelativeVolatilityIndex": {},
        "RSquared": {},
        "SectorRotationModel": {},
        "Trendflex": {},
        "TrendQuality": {},
        "UltimateOscillator": {}
    },
    "Moving Averages": {
        "AdaptiveEMA": {},
        "AnchoredVWAP": {},
        "DMA": {},
        "DEMA": {},
        "DisplacedEMA": {},
        "EhlersRoofingFilter": {},
        "EMA": {},
        "HullMovingAvg": {},
        "KeltnerChannels": {},
        "MACD": {},
        "MACDHistogram": {},
        "MACDHistogramCrossover": {},
        "MACDTwoLines": {},
        "MACDWithPrices": {},
        "MovAvgAdaptive": {},
        "MovAvgBands": {},
        "MovAvgBandWidth": {},
        "MovAvgExponential": {},
        "MovAvgEnvelope": {},
        "MovAvgExpRibbon": {},
        "MovAvgTriangular": {},
        "MovAvgWeighted": {},
        "MovingAvgCrossover": {},
        "MovAvgTwoLines": {},
        "RainbowAverage": {},
        "TEMA": {},
        "VWAP": {},
        "VariableMA": {}
    },
    "Oscillators": {
        "AwesomeOscillator": {},
        "ChaikinOscillator": {},
        "ChaikinVolatility": {},
        "ChandeMomentumOscillator": {},
        "EhlersAutocorrelation": {},
        "ElliotOscillator": {},
        "ErgodicOsc": {},
        "MACDHistogram": {},
        "MACDTwoLines": {},
        "Momentum": {},
        "StochasticFast": {},
        "StochasticFull": {},
        "StochasticFullDiff": {},
        "StochasticMACD": {},
        "StochasticSlow": {},
        "StochRSI": {},
        "TRIX": {},
        "UltimateOscillator": {},
        "RelativeMomentumIndex": {},
        "RocketRSI": {},
        "SchaffTrendCycle": {}
    },
    "Volatility Indicators": {
        "AccelerationBands": {},
        "ATR": {},
        "ATRHighSMABreakoutsFilter": {},
        "ATRTrailingStop": {},
        "BollingerBands": {},
        "BollingerBandsCrossover": {},
        "BollingerBandwidth": {},
        "BollingerPercentB": {},
        "ExponentialDeviationBands": {},
        "HistoricalVolatility": {},
        "ImpliedVolatility": {},
        "KeltnerChannels": {},
        "RelativeVolatilityIndex": {},
        "StandardDeviation": {},
        "VolatilityStdDev": {},
        "VolatilitySwitch": {},
        "VortexIndicator": {},
        "WilliamsAD": {},
        "WilliamsPercentR": {}
    },
    "Momentum Indicators": {
        "Momentum": {},
        "RelativeStrength": {},
        "RSI": {},
        "RSICrossover": {},
        "StochasticMomentumIndex": {},
        "MACDWithPrices": {},
        "MomentumSMA": {},
        "AwesomeOscillator": {},
        "ChaikinMoneyFlow": {},
        "ForceIndex": {},
        "Impulse": {},
        "MomentumCrossover": {},
        "MomentumPercent": {},
        "MomentumPercentDiff": {},
        "MomentumSMA": {},
        "CCI": {},
        "CCIAverage": {},
        "ChaikinMoneyFlow": {},
        "EaseOfMovement": {},
        "EhlersStochastic": {},
        "FisherTransform": {},
        "ROC": {},
        "RateOfChange": {},
        "RateOfChangeCrossover": {},
        "RateOfChangeWithBands": {}
    },
    "Cycle Indicators": {
        "EhlersDecyclerOscillator": {},
        "EhlersAutocorrelationPeriodogram": {},
        "CycleTrendAnalytics": {},
        "FisherTransform": {},
        "FourierSeriesIndicator": {},
        "MESASineWave": {},
        "EhlersStochastic": {},
        "SuperPassbandFilter": {},
        "VossPredictiveFilter": {},
        "CycleTrendAnalytics": {},
        "CorrelationCycleAngle": {},
        "CorrelationCycleIndicator": {},
        "CorrelationCycleMarketState": {}
    },
    "Volume-Weighted Indicators": {
        "AccumDist": {},
        "AccumDistBuyPr": {},
        "OnBalanceVolume": {},
        "OnBalanceVolumeModified": {},
        "VolumeAccumulation": {},
        "VolumeWeightedMACD": {},
        "VWAP": {},
        "KlingerOscillator": {}
    },
    "Support and Resistance Indicators": {
        "CamarillaPoints": {},
        "DarvasBox": {},
        "PivotPoints": {},
        "PersonsPivots": {},
        "ZigZagHighLow": {},
        "ZigZagPercent": {},
        "ZigZagTrendPercent": {},
        "ZigZagSign": {},
        "ZigZagTrendSign": {}
    },
    "Miscellaneous Indicators": {
        "Beta": {},
        "Beta2": {},
        "ForecastOscillator": {},
        "Correlation": {},
        "PriceVolumeRank": {},
        "RelativeVolumeStDev": {},
        "MedianPrice": {},
        "MonkeyBars": {},
        "StandardError": {},
        "StandardErrorBands": {},
        "StandardErrorChannel": {},
        "StandardDevChannel": {},
        "DeviationScaledMovAvg": {},
        "DeviationScaledOscillator": {},
        "RDOC": {},
        "QStick": {},
        "RangeBands": {},
        "RangeIndicator": {},
        "ZigZagHighLow": {},
        "ZigZagPercent": {},
        "ZigZagTrendPercent": {},
        "ZigZagTrendSign": {}
    }
}
