replayer:
    basefiles:
        commodity: ./cfg/assets_cfg/stk_comms.json  #品种列表
        # covermode:  0-开平, 1-区分平今, 3-不分开平
        # pricemode:  0-支持限价市价, 1-只支持限价, 2-只支持市价  
        # category :  20-币币SPOT, 21-永续SWAP, 22-期货Future, 23-币币杠杆Margin
        # trademode:  0-多空, 1-做多, 2-做多T+1
        contract: ./cfg/assets_list/stocks.json     #合约列表
        holiday: ./cfg/misc/holidays.json           #节假日列表
        hot: ./cfg/assets_list/hots.json            #主力合约映射表
        session: ./cfg/sessions/sessions.json   #交易时间模板
    stime: 200001010930         #回测开始时间，精确到分钟
    etime: 200001280930         #回测结束时间，精确到分钟
    fees: ./cfg/fees/fees_stk.json   #佣金配置文件
    mode: wtp   #回测历史数据存储，csv或者bin/wtp，其中bin/wtp都是一个意思
    store:
        module: WtDataStorage   #历史数据存储模块，如果是csv，该配置不生效
        path: ./storage/       #历史数据存储跟目录
env:
    mocker: cta                 #回测引擎，cta/sel/hft/exec/uf

replayer:
    basefiles:
        commodity: ../common/commodities.json
        contract: ../common/contracts.json
        holiday: ../common/holidays.json
        hot: ../common/hots.json
        session: ../common/sessions.json
    mode: wtp
    path: ../../storage/
    fees: ../common/fees.json
    adjfactor: adjfactors.json
    stime: 202101040931
    etime: 202101121500
    tick: true
env:
    mocker: hft
hft0:
    error_rate: 30
    module: WzHftStraFact
    strategy:
        name: OrderImbalance
        params:
            active_sections:
            -   end: 1457
                start: 931
            beta_0: 0.01171
            beta_oi:
            - 0.00489
            - 0.00319
            - 0.00109
            - 0.00044
            - 0.00036
            - 0.00164
            beta_r: 0.01371
            beta_rou:
            - 0.02654
            - -0.03374
            - -0.00443
            - 0.00421
            - -0.00117
            - -0.00404
            code: CFFEX.IF.HOT
            count: 6
            expsecs: 5
            freq: 20
            lots: 1
            offset: 0
            reserve: 0
            stock: false
            threshold: 0.3
    use_newpx: true