replayer:
    mode: bin   #回测历史数据存储，csv或者bin/wtp，其中bin/wtp都是一个意思
    basefiles:
        commodity: ./config/cpt_comms.json  #品种列表
        # covermode:  0-开平, 1-区分平今, 3-不分开平
        # pricemode:  0-支持限价市价, 1-只支持限价, 2-只支持市价  
        # category :  20-币币SPOT, 21-永续SWAP, 22-期货Future, 23-币币杠杆Margin
        # trademode:  0-多空, 1-做多, 2-做多T+1
        contract: ./config/cpt_assets.json          #合约列表
        holiday: ./config/cpt_holidays.json        #节假日列表
        session: ./config/cpt_sessions.json        #交易时间模板
    fees: ./config/cpt_fees.json                   #佣金配置文件
    stime: 200001010000                     #回测开始时间，精确到分钟
    etime: 210001010000                    #回测结束时间，精确到分钟
    store:
        module: WtDataStorage   #历史数据存储模块，如果是csv，该配置不生效
        path: ../storage/       #历史数据存储跟目录
env:
    mocker: cta                 #回测引擎，cta/sel/hft/exec/uf
    # slippage: 0                 # 滑点

# cta:                # 策略工厂配置
#     module: WtCtaStraFact.dll       # 策略生成器模块名
#     strategy:                       # 策略配置
#         id: cpt_ml                  # 策略id
#         name: Crypto_ML             # 策略名
#         params:                     # 策略参数
#             code: Binance.UM
#             count: 50
#             period: m1
#             days: 30
#             k1: 0.6
#             k2: 0.6
#             stock: false