root:                   # 根日志对象的配置，通常是框架信息
    level: debug        # 日志等级
    async: false        # 是否异步
    sinks:              # 输出流的配置，即日志信息会被输出到哪些位置
    -   type: basic_file_sink                           # 类型，基本的文件输出
        filename: logs/Runner.log                     # 日志文件保存位置
        pattern: '[%Y.%m.%d %H: %M: %S - %-5l] %v'      # 日志输出模板
        truncate: true                                  # 日志是否自动截断，截断可以避免日志文件过大
        type: console_sink                              # 输出到控制台
        pattern: '[%m.%d %H: %M: %S - %^%-5l%$] %v'
dyn_pattern: 
    strategy: 
        level: debug
        async: false
        sinks: 
        -   type: basic_file_sink
            filename: logs/Strategy_%s.log
            pattern: '[%Y.%m.%d %H: %M: %S - %-5l] %v'
            truncate: false