qlib_init:
    provider_uri: "./.qlib/qlib_data/cn_data"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2018-01-01
    end_time: 2020-08-01
    fit_start_time: 2018-01-01
    fit_end_time: 2018-12-31
    instruments: *market
port_analysis_config: &port_analysis_config
    executor:
        # class: NestedExecutor
        class: SimulatorExecutor
        module_path: qlib.backtest.executor
        kwargs:
            time_per_step: day
            generate_portfolio_metrics: True
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2020-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: XGBModel
        module_path: qlib.contrib.model.xgboost
        kwargs:
            seed: 1000
            eval_metric: rmse # rmse or mse
            colsample_bytree: 0.8879
            eta: 0.0421
            max_depth: 8
            n_estimators: 647
            subsample: 0.8789
            nthread: 20
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2018-01-01, 2018-12-31]
                valid: [2019-01-01, 2019-12-31]
                test: [2020-01-01, 2020-08-01]
